syntax on
set foldmethod=indent
set backspace=indent,eol,start
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set number
set relativenumber
set scrolloff=999
set autoindent
set smartindent
